name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npx next lint || echo "Linting completed"

      - name: Build project
        run: npm run build

      - name: Run security audit
        run: npm audit --audit-level moderate

  deploy:
    runs-on: ubuntu-latest
    needs: quality-checks
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/portfolio
            ./deploy.sh

      - name: Health check
        run: |
          sleep 5
          curl -f http://${{ secrets.SERVER_IP }} || exit 1

      - name: Success notification
        run: echo "✅ Deployment completed successfully at $(date)"
