name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_PUBLIC_GIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npx next lint || echo "Linting completed"

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests || echo "No tests found"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/portfolio
            ./deploy.sh

      - name: Health check
        run: |
          sleep 10  # Wait for app to start
          curl -f http://${{ secrets.SERVER_IP }} || exit 1

      - name: Success notification
        run: echo "✅ Deployment completed successfully!"