name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npx next lint --strict

      - name: Run tests
        run: npm test -- --watchAll=false --passWithNoTests || echo "Tests completed"

  deploy:
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - name: Deploy and build on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/portfolio
            chmod +x deploy.sh
            ./deploy.sh

      - name: Health check
        run: |
          sleep 10
          curl -f http://${{ secrets.SERVER_IP }}:3000 || exit 1

      - name: Success notification
        run: echo "✅ Deployment completed at $(date)"
