name: Portfolio CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_PUBLIC_GIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Clean install
        run: |
          # Remove any existing node_modules and lock files
          rm -rf node_modules package-lock.json

          # Create fresh package-lock.json
          npm install --package-lock-only

          # Install all dependencies
          npm ci

          # Force install critical dependencies
          npm install --no-save eslint@^8.0.0 eslint-config-next@^14.0.0 autoprefixer@^10.0.0 postcss@^8.0.0

      - name: Build project
        run: npm run build

      - name: Run linting
        run: npm run lint

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: |
            .next
            public
            package.json
            next.config.js
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: ./deploy

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/portfolio
            ./deploy.sh

      - name: Health check
        run: |
          curl -f http://${{ secrets.SERVER_IP }} || exit 1
